container:
    build: .
    #image: udaysh/php_v7.2
    labels:
        - "com.lowecloud.proxy=php.docker"
    volumes:
        - "./manifest/config/nginx.conf:/etc/nginx/nginx.conf:ro"
        - "./manifest/config/x-debug.ini:/usr/local/etc/php/conf.d/x-debug.ini:ro"
        - "./manifest/config/mcrypt.ini:/usr/local/etc/php/conf.d/mcrypt.ini:ro"
        - "./manifest/config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro"
        - "./app:/app"

